# Generated by Django 4.1.7 on 2023-02-28 01:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='categoria2',
        ),
    ]
